project:
  name: "example-project"
  description: "Example project for AI E2E Test Framework"
  base_url: "https://example.com"
  timeout: 30000

browser:
  type: "chromium"
  headless: true
  viewport:
    width: 1280
    height: 720

authentication:
  method: "form"
  username: "${TEST_USERNAME}"
  password: "${TEST_PASSWORD}"
  login_url: "/login"
  success_indicator: ".dashboard"

test_data:
  users:
    test_user:
      email: "test@example.com"
      password: "password123"
      name: "Test User"
  
  products:
    sample_product:
      name: "Sample Product"
      price: 29.99
      category: "Electronics"

environments:
  development:
    base_url: "http://localhost:3000"
    debug: true
  
  staging:
    base_url: "https://staging.example.com" 
    debug: false
  
  production:
    base_url: "https://example.com"
    debug: false

execution:
  retry_count: 3
  retry_delay: 1000
  screenshot_on_failure: true

reporting:
  format: ["json", "html"]
  output_dir: "./test-results"
  include_screenshots: true
  include_accessibility: true