project:
  name: 'example-project'
  description: 'Example project for AI E2E Test Framework'
  timeout: 30000

browser:
  type: 'chromium'
  headless: true
  viewport:
    width: 1280
    height: 720

urls:
  main: 'http://localhost:3000'

test_data:
  valid:
    username: 'test@example.com'
    password: 'password123'

  invalid:
    username: 'wrong@example.com'
    password: 'wrongpass'

execution:
  retry_count: 3
  retry_delay: 1000
  screenshot_on_failure: true

reporting:
  format: ['json', 'html']
  output_dir: './test-results'
  include_screenshots: true
  include_accessibility: true
